import type { Area, RecommendationResponse, Scene } from "./types";

export const areas: Area[] = [
  {
    code: "xinjiekou",
    city: "南京",
    name: "新街口",
    district: "秦淮区",
    longitude: 118.784,
    latitude: 32.041,
    description: "适合约会、晚餐、咖啡和轻量逛街的城市中心。",
  },
  {
    code: "xuanwu-lake",
    city: "南京",
    name: "玄武湖",
    district: "玄武区",
    longitude: 118.797,
    latitude: 32.071,
    description: "适合散步、独处、周末半日和轻户外。",
  },
  {
    code: "laomendong",
    city: "南京",
    name: "老门东",
    district: "秦淮区",
    longitude: 118.795,
    latitude: 32.015,
    description: "适合朋友聚会、城市漫游和夜晚氛围路线。",
  },
  {
    code: "hexi",
    city: "南京",
    name: "河西",
    district: "建邺区",
    longitude: 118.728,
    latitude: 32.004,
    description: "适合商场、展览、室内活动和雨天安排。",
  },
];

export const scenes: Scene[] = [
  { code: "eat", name: "吃什么", subtitle: "下班后舒服一点", icon: "Utensils", poiTypes: ["餐厅", "咖啡"] },
  { code: "date", name: "约会去哪", subtitle: "自然、不尴尬", icon: "Heart", poiTypes: ["咖啡", "餐厅", "公园"] },
  { code: "weekend", name: "周末去哪", subtitle: "半日城市漫游", icon: "Sun", poiTypes: ["展览", "街区", "公园"] },
  { code: "alone", name: "一个人去哪", subtitle: "安静放空", icon: "BookOpen", poiTypes: ["书店", "咖啡", "公园"] },
  { code: "rain", name: "雨天去哪", subtitle: "室内也好逛", icon: "CloudRain", poiTypes: ["商场", "书店", "展览"] },
  { code: "friends", name: "朋友聚会", subtitle: "好聊、好吃、好收尾", icon: "Users", poiTypes: ["餐厅", "酒馆", "街区"] },
  { code: "coffee", name: "咖啡甜品", subtitle: "坐一会儿，聊聊天", icon: "Coffee", poiTypes: ["咖啡", "甜品"] },
  { code: "culture", name: "看展", subtitle: "有内容，也好拍", icon: "Landmark", poiTypes: ["展览", "美术馆", "博物馆"] },
  { code: "show", name: "电影演出", subtitle: "看完还能接着走", icon: "Ticket", poiTypes: ["电影院", "剧院", "演出"] },
  { code: "walk", name: "城市漫步", subtitle: "慢慢走一段", icon: "Footprints", poiTypes: ["街区", "公园", "景点"] },
  { code: "nightlife", name: "夜生活", subtitle: "小酌、夜游、收尾", icon: "Moon", poiTypes: ["酒吧", "夜市", "街区"] },
  { code: "family", name: "亲子", subtitle: "轻松、安全、少折腾", icon: "Baby", poiTypes: ["亲子", "公园", "商场"] },
  { code: "pet", name: "宠物友好", subtitle: "带宠也自在", icon: "PawPrint", poiTypes: ["公园", "宠物友好", "咖啡"] },
  { code: "work", name: "学习办公", subtitle: "安静、插座、久坐", icon: "Laptop", poiTypes: ["图书馆", "咖啡", "自习室"] },
  { code: "sport", name: "运动放松", subtitle: "轻运动，恢复状态", icon: "Dumbbell", poiTypes: ["健身", "运动", "公园"] },
  { code: "shopping", name: "购物逛街", subtitle: "买点东西，也吃点", icon: "ShoppingBag", poiTypes: ["商场", "购物", "餐厅"] },
  { code: "photo", name: "拍照出片", subtitle: "有画面感，别太挤", icon: "Camera", poiTypes: ["景点", "街区", "展览"] },
  { code: "halfday", name: "短途半日", subtitle: "轻计划，不赶路", icon: "Route", poiTypes: ["景点", "街区", "咖啡"] },
  { code: "lodging", name: "住宿/住一晚", subtitle: "附近过夜，安心休息", icon: "Bed", poiTypes: ["酒店", "民宿", "宾馆"] },
];

export const mockRecommendation: RecommendationResponse = {
  recordId: "mock-rec-001",
  requestSummary: "南京 · 新街口 · 第一次约会，预算 300，不想太吵",
  aiNotice:
    "本方案由 AI 基于真实地点数据生成，仅供出行参考。营业时间、价格、人流和排队情况可能变化，请以地图、商家或现场信息为准。",
  plans: [
    {
      id: "plan-soft-date",
      title: "轻松不尴尬的第一次见面路线",
      summary: "先从安静咖啡开始，再去氛围感晚餐，最后用散步自然收尾。",
      tags: ["约会", "不太吵", "自然收尾"],
      budgetPerPerson: 238,
      totalDistanceMeters: 1800,
      totalDurationMinutes: 190,
      routeText: "步行与短途打车结合，动线集中在新街口与长江路一带。",
      riskTips: ["晚餐高峰可能需要排队", "散步段请以当天天气为准"],
      stops: [
        {
          order: 1,
          stayMinutes: 55,
          reason: "适合先坐下来轻松聊天，空间不会太正式，也不容易冷场。",
          poi: {
            id: "poi-librairie-avantgarde",
            source: "custom",
            sourcePoiId: "custom-nj-001",
            name: "先锋书店五台山总店",
            address: "南京市鼓楼区广州路173号",
            city: "南京",
            district: "鼓楼区",
            longitude: 118.773,
            latitude: 32.051,
            category: "书店/咖啡",
            distanceMeters: 980,
            avgPrice: 45,
            rating: 4.7,
            openingHours: "10:00-21:00",
            tags: ["安静", "有话题", "适合初见"],
          },
        },
        {
          order: 2,
          stayMinutes: 85,
          reason: "晚餐氛围轻松，预算可控，适合从咖啡自然过渡到正餐。",
          poi: {
            id: "poi-deji-food",
            source: "custom",
            sourcePoiId: "custom-nj-002",
            name: "德基广场餐饮区",
            address: "南京市玄武区中山路18号",
            city: "南京",
            district: "玄武区",
            longitude: 118.785,
            latitude: 32.045,
            category: "商场/餐厅",
            distanceMeters: 520,
            avgPrice: 160,
            rating: 4.6,
            openingHours: "10:00-22:00",
            tags: ["选择多", "交通方便", "预算弹性"],
          },
        },
        {
          order: 3,
          stayMinutes: 45,
          reason: "如果气氛不错，可以沿着长江路慢慢走一段，让约会自然结束。",
          riskTip: "雨天建议改为商场内散步。",
          poi: {
            id: "poi-changjiang-road",
            source: "custom",
            sourcePoiId: "custom-nj-003",
            name: "长江路文化街区",
            address: "南京市玄武区长江路沿线",
            city: "南京",
            district: "玄武区",
            longitude: 118.793,
            latitude: 32.047,
            category: "街区",
            distanceMeters: 780,
            avgPrice: 0,
            rating: 4.5,
            openingHours: "全天",
            tags: ["散步", "城市感", "自然收尾"],
          },
        },
      ],
    },
    {
      id: "plan-rainy-indoor",
      title: "雨天也舒展的室内半日",
      summary: "把书店、展览和晚餐放在一条短动线上，减少户外暴露。",
      tags: ["雨天", "室内", "低步行"],
      budgetPerPerson: 186,
      totalDistanceMeters: 1200,
      totalDurationMinutes: 210,
      routeText: "主要集中在河西室内空间，适合天气不稳定时使用。",
      riskTips: ["展览档期可能变化", "热门餐厅建议提前取号"],
      stops: [
        {
          order: 1,
          stayMinutes: 70,
          reason: "室内空间稳定，适合先慢下来，不受天气影响。",
          poi: {
            id: "poi-jinling-library",
            source: "custom",
            sourcePoiId: "custom-nj-004",
            name: "金陵图书馆",
            address: "南京市建邺区乐山路158号",
            city: "南京",
            district: "建邺区",
            longitude: 118.724,
            latitude: 32.003,
            category: "图书馆",
            distanceMeters: 450,
            avgPrice: 0,
            rating: 4.7,
            openingHours: "09:00-17:30",
            tags: ["安静", "室内", "省钱"],
          },
        },
        {
          order: 2,
          stayMinutes: 80,
          reason: "展览停留感更强，适合雨天下午安排一段有内容的时间。",
          poi: {
            id: "poi-poly-theatre",
            source: "custom",
            sourcePoiId: "custom-nj-005",
            name: "南京保利大剧院周边展演空间",
            address: "南京市建邺区邺城路6号",
            city: "南京",
            district: "建邺区",
            longitude: 118.721,
            latitude: 32.009,
            category: "展演空间",
            distanceMeters: 680,
            avgPrice: 80,
            rating: 4.6,
            openingHours: "以展演信息为准",
            tags: ["室内", "出片", "不赶"],
          },
        },
        {
          order: 3,
          stayMinutes: 60,
          reason: "最后用商场晚餐收尾，交通和选择都更稳。",
          poi: {
            id: "poi-golden-eagle-world",
            source: "custom",
            sourcePoiId: "custom-nj-006",
            name: "金鹰世界",
            address: "南京市建邺区应天大街888号",
            city: "南京",
            district: "建邺区",
            longitude: 118.736,
            latitude: 32.012,
            category: "商场/餐厅",
            distanceMeters: 1100,
            avgPrice: 120,
            rating: 4.5,
            openingHours: "10:00-22:00",
            tags: ["选择多", "室内", "好收尾"],
          },
        },
      ],
    },
  ],
};
