import type { Area, RecommendationResponse, Scene } from "./types";

export const areas: Area[] = [
  {
    code: "xinjiekou",
    city: "南京",
    name: "新街口",
    district: "秦淮区",
    longitude: 118.784,
    latitude: 32.041,
    description: "适合约会、晚餐、咖啡和轻量逛街的城市中心。",
  },
  {
    code: "xuanwu-lake",
    city: "南京",
    name: "玄武湖",
    district: "玄武区",
    longitude: 118.797,
    latitude: 32.071,
    description: "适合散步、独处、周末半日和轻户外。",
  },
  {
    code: "laomendong",
    city: "南京",
    name: "老门东",
    district: "秦淮区",
    longitude: 118.795,
    latitude: 32.015,
    description: "适合朋友聚会、城市漫游和夜晚氛围路线。",
  },
  {
    code: "hexi",
    city: "南京",
    name: "河西",
    district: "建邺区",
    longitude: 118.728,
    latitude: 32.004,
    description: "适合商场、展览、室内活动和雨天安排。",
  },
];

export const scenes: Scene[] = [
  { code: "eat", name: "吃饭", subtitle: "好好吃一顿", icon: "Utensils", poiTypes: ["餐厅", "中餐", "西餐"] },
  { code: "hotpot_bbq", name: "火锅烧烤", subtitle: "热乎，适合聚", icon: "Flame", poiTypes: ["火锅", "烧烤", "串串"] },
  { code: "coffee", name: "咖啡甜品", subtitle: "坐一会儿，聊聊天", icon: "Coffee", poiTypes: ["咖啡", "甜品", "茶饮"] },
  { code: "afternoon_tea", name: "下午茶", subtitle: "轻松坐坐", icon: "CupSoda", poiTypes: ["下午茶", "茶饮", "甜品"] },
  { code: "nightlife", name: "夜宵小酒", subtitle: "夜里也好收尾", icon: "Moon", poiTypes: ["夜宵", "小酒馆", "酒吧"] },
  { code: "local_snack", name: "地方小吃", subtitle: "烟火气，随便吃", icon: "Soup", poiTypes: ["小吃", "地方菜", "夜市"] },
  { code: "light_meal", name: "轻食简餐", subtitle: "快一点，清爽点", icon: "Salad", poiTypes: ["轻食", "简餐", "沙拉"] },
  { code: "date_dining", name: "约会餐厅", subtitle: "氛围好，不尴尬", icon: "Heart", poiTypes: ["餐厅", "西餐", "日料"] },
  { code: "movie", name: "看电影", subtitle: "看完还能接着走", icon: "Clapperboard", poiTypes: ["电影院"] },
  { code: "ktv", name: "KTV唱歌", subtitle: "热闹一点，好收尾", icon: "Mic2", poiTypes: ["KTV", "量贩式KTV", "音乐娱乐"] },
  { code: "internet_cafe", name: "网吧电竞", subtitle: "开黑，电竞感", icon: "Gamepad2", poiTypes: ["网吧", "电竞馆", "电竞酒店"] },
  { code: "billiards_boardgames", name: "台球棋牌", subtitle: "轻松玩一会儿", icon: "Dice5", poiTypes: ["台球", "棋牌室", "桌游"] },
  { code: "arcade", name: "游乐场", subtitle: "轻娱乐，不费脑", icon: "FerrisWheel", poiTypes: ["游乐场", "电玩城", "亲子乐园"] },
  { code: "culture", name: "展览演出", subtitle: "有内容，也好拍", icon: "Landmark", poiTypes: ["展览", "美术馆", "博物馆", "剧院", "演出"] },
  { code: "shopping", name: "逛商场购物", subtitle: "买点东西，也吃点", icon: "ShoppingBag", poiTypes: ["商场", "购物中心", "步行街"] },
  { code: "walk", name: "城市漫步", subtitle: "慢慢走一段", icon: "Footprints", poiTypes: ["街区", "公园", "步行街"] },
  { code: "massage", name: "按摩足疗", subtitle: "松一松，恢复状态", icon: "HandHeart", poiTypes: ["按摩", "足疗", "养生"] },
  { code: "bath_spa", name: "洗浴汗蒸", subtitle: "热乎放松一下", icon: "Waves", poiTypes: ["洗浴", "汗蒸", "温泉"] },
  { code: "lodging", name: "酒店住宿", subtitle: "附近住一晚", icon: "Bed", poiTypes: ["酒店", "住宿", "宾馆", "民宿", "快捷酒店", "星级酒店"] },
  { code: "quiet_sit", name: "安静坐坐", subtitle: "放空，不被打扰", icon: "Sofa", poiTypes: ["咖啡", "书店", "茶馆"] },
  { code: "park_walk", name: "公园散步", subtitle: "走走，透透气", icon: "Trees", poiTypes: ["公园", "绿地", "景区"] },
  { code: "bookstore_coffee", name: "书店咖啡", subtitle: "安静看会儿书", icon: "BookOpen", poiTypes: ["书店", "咖啡", "图书馆"] },
  { code: "photo", name: "拍照出片", subtitle: "有画面感，别太挤", icon: "Camera", poiTypes: ["景点", "街区", "展览"] },
  { code: "sport", name: "运动放松", subtitle: "轻运动，恢复状态", icon: "Dumbbell", poiTypes: ["运动", "健身", "公园"] },
  { code: "tonight", name: "今晚随便安排", subtitle: "别费脑，直接走", icon: "Sparkles", poiTypes: ["餐厅", "咖啡", "商场"] },
  { code: "halfday", name: "半天城市路线", subtitle: "半天刚刚好", icon: "Route", poiTypes: ["景点", "街区", "咖啡"] },
  { code: "date", name: "约会不尴尬", subtitle: "自然一点", icon: "Heart", poiTypes: ["咖啡", "餐厅", "公园"] },
  { code: "after_work", name: "下班放松一下", subtitle: "恢复一点状态", icon: "Sunset", poiTypes: ["餐厅", "按摩", "咖啡"] },
  { code: "weekend", name: "周末轻松逛逛", subtitle: "有内容，不折腾", icon: "Sun", poiTypes: ["展览", "街区", "公园"] },
  { code: "friends", name: "朋友见面安排", subtitle: "好聊，方便收尾", icon: "Users", poiTypes: ["餐厅", "KTV", "台球"] },
  { code: "rain", name: "雨天室内方案", subtitle: "少走路，也舒服", icon: "CloudRain", poiTypes: ["商场", "书店", "展览"] },
  { code: "alone", name: "一个人也舒服", subtitle: "安静放空一下", icon: "BookOpen", poiTypes: ["书店", "咖啡", "公园"] },
  { code: "show", name: "电影演出", subtitle: "旧场景兼容", icon: "Ticket", poiTypes: ["电影院", "剧院", "演出"] },
  { code: "family", name: "亲子", subtitle: "旧场景兼容", icon: "Baby", poiTypes: ["亲子", "公园", "商场"] },
  { code: "pet", name: "宠物友好", subtitle: "旧场景兼容", icon: "PawPrint", poiTypes: ["公园", "宠物友好", "咖啡"] },
  { code: "work", name: "学习办公", subtitle: "旧场景兼容", icon: "Laptop", poiTypes: ["图书馆", "咖啡", "自习室"] },
];

export const mockRecommendation: RecommendationResponse = {
  recordId: "mock-rec-001",
  requestSummary: "南京 · 新街口 · 第一次约会，预算 300，不想太吵",
  aiNotice:
    "本方案由 AI 基于真实地点数据生成，仅供出行参考。营业时间、价格、人流和排队情况可能变化，请以地图、商家或现场信息为准。",
  plans: [
    {
      id: "plan-soft-date",
      title: "轻松不尴尬的第一次见面路线",
      summary: "先从安静咖啡开始，再去氛围感晚餐，最后用散步自然收尾。",
      tags: ["约会", "不太吵", "自然收尾"],
      budgetPerPerson: 238,
      totalDistanceMeters: 1800,
      totalDurationMinutes: 190,
      routeText: "步行与短途打车结合，动线集中在新街口与长江路一带。",
      riskTips: ["晚餐高峰可能需要排队", "散步段请以当天天气为准"],
      stops: [
        {
          order: 1,
          stayMinutes: 55,
          reason: "适合先坐下来轻松聊天，空间不会太正式，也不容易冷场。",
          poi: {
            id: "poi-librairie-avantgarde",
            source: "custom",
            sourcePoiId: "custom-nj-001",
            name: "先锋书店五台山总店",
            address: "南京市鼓楼区广州路173号",
            city: "南京",
            district: "鼓楼区",
            longitude: 118.773,
            latitude: 32.051,
            category: "书店/咖啡",
            distanceMeters: 980,
            avgPrice: 45,
            rating: 4.7,
            openingHours: "10:00-21:00",
            tags: ["安静", "有话题", "适合初见"],
          },
        },
        {
          order: 2,
          stayMinutes: 85,
          reason: "晚餐氛围轻松，预算可控，适合从咖啡自然过渡到正餐。",
          poi: {
            id: "poi-deji-food",
            source: "custom",
            sourcePoiId: "custom-nj-002",
            name: "德基广场餐饮区",
            address: "南京市玄武区中山路18号",
            city: "南京",
            district: "玄武区",
            longitude: 118.785,
            latitude: 32.045,
            category: "商场/餐厅",
            distanceMeters: 520,
            avgPrice: 160,
            rating: 4.6,
            openingHours: "10:00-22:00",
            tags: ["选择多", "交通方便", "预算弹性"],
          },
        },
        {
          order: 3,
          stayMinutes: 45,
          reason: "如果气氛不错，可以沿着长江路慢慢走一段，让约会自然结束。",
          riskTip: "雨天建议改为商场内散步。",
          poi: {
            id: "poi-changjiang-road",
            source: "custom",
            sourcePoiId: "custom-nj-003",
            name: "长江路文化街区",
            address: "南京市玄武区长江路沿线",
            city: "南京",
            district: "玄武区",
            longitude: 118.793,
            latitude: 32.047,
            category: "街区",
            distanceMeters: 780,
            avgPrice: 0,
            rating: 4.5,
            openingHours: "全天",
            tags: ["散步", "城市感", "自然收尾"],
          },
        },
      ],
    },
    {
      id: "plan-rainy-indoor",
      title: "雨天也舒展的室内半日",
      summary: "把书店、展览和晚餐放在一条短动线上，减少户外暴露。",
      tags: ["雨天", "室内", "低步行"],
      budgetPerPerson: 186,
      totalDistanceMeters: 1200,
      totalDurationMinutes: 210,
      routeText: "主要集中在河西室内空间，适合天气不稳定时使用。",
      riskTips: ["展览档期可能变化", "热门餐厅建议提前取号"],
      stops: [
        {
          order: 1,
          stayMinutes: 70,
          reason: "室内空间稳定，适合先慢下来，不受天气影响。",
          poi: {
            id: "poi-jinling-library",
            source: "custom",
            sourcePoiId: "custom-nj-004",
            name: "金陵图书馆",
            address: "南京市建邺区乐山路158号",
            city: "南京",
            district: "建邺区",
            longitude: 118.724,
            latitude: 32.003,
            category: "图书馆",
            distanceMeters: 450,
            avgPrice: 0,
            rating: 4.7,
            openingHours: "09:00-17:30",
            tags: ["安静", "室内", "省钱"],
          },
        },
        {
          order: 2,
          stayMinutes: 80,
          reason: "展览停留感更强，适合雨天下午安排一段有内容的时间。",
          poi: {
            id: "poi-poly-theatre",
            source: "custom",
            sourcePoiId: "custom-nj-005",
            name: "南京保利大剧院周边展演空间",
            address: "南京市建邺区邺城路6号",
            city: "南京",
            district: "建邺区",
            longitude: 118.721,
            latitude: 32.009,
            category: "展演空间",
            distanceMeters: 680,
            avgPrice: 80,
            rating: 4.6,
            openingHours: "以展演信息为准",
            tags: ["室内", "出片", "不赶"],
          },
        },
        {
          order: 3,
          stayMinutes: 60,
          reason: "最后用商场晚餐收尾，交通和选择都更稳。",
          poi: {
            id: "poi-golden-eagle-world",
            source: "custom",
            sourcePoiId: "custom-nj-006",
            name: "金鹰世界",
            address: "南京市建邺区应天大街888号",
            city: "南京",
            district: "建邺区",
            longitude: 118.736,
            latitude: 32.012,
            category: "商场/餐厅",
            distanceMeters: 1100,
            avgPrice: 120,
            rating: 4.5,
            openingHours: "10:00-22:00",
            tags: ["选择多", "室内", "好收尾"],
          },
        },
      ],
    },
  ],
};
